name: linter

on: [push]
jobs:
  flake8-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependecies
        run: |
          python3 -m pip install poetry
          poetry install
      - name: Run linter
        run: |
          make linter
